### ISSUE TITLE
Data Processing Scripts

### ISSUE THREAD

**Issue by t1101675** [MANGA-UOFA/LMReward#1]
Nice work!

I'm wondering whether you could also release the scripts for data processing or the processed `.src` and `.tgt` files. It would be very helpful for reproducing the results and further extension.

**Comment by yongchanghao** [comment]
Thank you for your interests. The .src and .tgt files are just the normal parallel text files. For example, if you want to replicate the results on DD, you can extract them from the csv files in [this repo](https://github.com/yq-wen/overlapping-datasets). There is no additional data processing step.

I will provide the scripts for extracting the csv file along with other improvements for replicating.

**Comment by t1101675** [comment]
Thanks!
